### ISSUE TITLE
Wroom-02

### ISSUE THREAD

**Issue by flyandi** [ikesato/eagle-libraries#1]
Howdy,

Thanks for the Wroom-02 component. It's not really an issue but more a question what Pin's need to be wired up. Are there the same as ESP-12 (http://cdn.instructables.com/FCH/0MSC/I697OYRQ/FCH0MSCI697OYRQ.LARGE.jpg) ? 

I assume that your GND1-4 are all already matched for that?

Thanks,

Andy

**Comment by ikesato** [comment]
Thanks for your comment.
The pin layout and count of ESP-12 and ESP-WROOM-02 are different.
Number of pins of the ESP-12 is 16 but, WROOM-02 is 18.
I recommend to use the ESP-12 library.

e.g.
https://github.com/autosportlabs/eagle_lbr/blob/master/ESP8266-ESP12.lbr

**Comment by flyandi** [comment]
Yeah I already figured it out. It seems that IO2 doesn't have to be pulled up as it is not a boot requirement on the WROOM-02. Everything else is the same as ESP-12.

**Comment by ikesato** [comment]
**Datasheet of WROOM-02**
http://doc.switch-science.com/datasheets/0C-ESP8266__WROOM_WiFi_Module_Datasheet__EN_v0.3.pdf

![screenshot_2015-08-29_11 34 30](https://cloud.githubusercontent.com/assets/2138831/9560176/0004da22-4e42-11e5-9635-7892a61ecd45.png)

### Flash Boot Mode (Boot Normally)

Pull-up IO0,IO2.
Pull-down IO15.

### UART Download Mode (Program from Arduino IDE)

Pull-up IO2.
Pull-down IO15, IO0.

Both mode always needs to be pull-up EN pin (pin number 2), and connect 3V3, GND pins.
